nmd 490 add controllers
Glipchik/Enlightenment pull request #11
Opened 2024-01-04 13:23 UTC by VadimZharikov

mapper config

add controllers

resolve

sync

add models, controllers, configure mapper

resolve

add generic service

make generic repo delete and getbyid return type to nullable entity

2024-01-04 14:01 UTC, Genresal commented on Client/EnlightenmentApp.API/Controllers/ChapterController.cs
> +    [ApiController]
possible **[Route("api/chapters")]** is better

2024-01-04 14:02 UTC, Glipchik requested changes

2024-01-04 14:02 UTC, Glipchik commented on Client/EnlightenmentApp.API/Enums/TagTypeEnum.cs
> +    public enum TagType
Let´s move all the enums to separate Domain layer and use it from all other layers

2024-01-04 14:02 UTC, Glipchik commented on Client/EnlightenmentApp.API/Controllers/ChapterController.cs
> +        // GET: api/<Controller>/5
Replace simple comments with the controller description notation

2024-01-05 08:25 UTC, Glipchik approved these changes

2024-01-05 08:39 UTC, Finka95 commented on Client/EnlightenmentApp.API/Program.cs
> +    //app.UseSwagger();
Remove this

2024-01-05 08:43 UTC, Finka95 approved these changes

2024-01-05 09:34 UTC, merged